### PR TITLE
Update for Commerce Products

### PR DESCRIPTION
**Pull request by amityweb**

### CODE REVIEW

**Comment by christianruhstaller** [comment]
This pull requests introduces a lot of duplicated code. I think that it would be good to refactor these  calls into function calls in the long run this will be beneficial for maintenance. 

To implement this nicely it need some time. We would appreciate it if you would to this, but if not we'll probably have a look at this in the near future.

**Comment by amityweb** [comment]
Yes I agree, I just need it done ASAP, but then would also like it in the next update to ensure if I update the plugin it does not override my changes. 

I wont have time to do this "nicely" as I work on customer projects with tight dealdines, hence my code is a fast code, not a nice code. 

As long as your next update includes a fix for this, then it doesn't matter if its 1 day or 1 month or 6 months for us, as its working for us now, we just need to make sure any future update has this in it so you can take your time to update it to your own way of coding. 

Hopefully our code can just help you. I think its only that one function I duplicated for Product that could be merged into one function and within check if its an entry or a Product. 

Thanks

**Comment by christianruhstaller** [comment]
If you don't want your changes overwritten, I recommend that you install your repository via composer and not ours. 
This is possible with composer, see following link for more information:

https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository

We can't guarantee that this change will be in our next release, so the only way for you to be safe is to maintain your own fork for the time and then change back.

**Comment by amityweb** [comment]
Well, no I disagree, I have reported an issue, and provided help to fix it, I think it be bad if you release a new version without this feature. The best action is just include it (or improved version) in your next release. Otherwise other people all have to use their own repos and starts to get messy, and how do we know you then have released a version with it? Just makes the whole thing more messy. 
Thanks!

P.S. we have auto updates using Manage WP.

**Comment by christianruhstaller** [comment]
With the release of version 0.4.0 this feature is included.

**Pull request closed without merging**
